/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as UrqlImport } from './routes/urql'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const UrqlRoute = UrqlImport.update({
  path: '/urql',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/urql': {
      id: '/urql'
      path: '/urql'
      fullPath: '/urql'
      preLoaderRoute: typeof UrqlImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/urql': typeof UrqlRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/urql': typeof UrqlRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/urql': typeof UrqlRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/urql'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/urql'
  id: '__root__' | '/' | '/urql'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  UrqlRoute: typeof UrqlRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  UrqlRoute: UrqlRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/urql"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/urql": {
      "filePath": "urql.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
