// app/router.tsx
import { createRouter as createTanStackRouter } from "@tanstack/react-router";
import { GraphProvider, client } from "./graphql/clientProvider";
import { ssr } from "./graphql/ssrExchange";
import { routeTree } from "./routeTree.gen";

export function createRouter() {
	const router = createTanStackRouter({
		routeTree,
		context: {
			client,
		},
		hydrate: (dehydrated) => {
			// Hydrate URQL with data passed by TSR, this is generated by dehydrate function in server router.
			ssr.restoreData(dehydrated.initialData);
		},

		Wrap: ({ children }) => <GraphProvider>{children}</GraphProvider>,
	});

	return router;
}
